version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webV1
    volumes:
      - ./src:/src
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 10
        python3 manage.py runserver 0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 4354
      MYSQL_ROOT_PASSWORD: 4354
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
