# Generated by Django 2.2.5 on 2022-05-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotData',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=255)),
                ('answers_ko', models.CharField(max_length=255)),
                ('labels', models.IntegerField()),
                ('answers_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
